# Generated by Django 5.1.1 on 2024-09-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atomic_number', models.PositiveIntegerField()),
                ('symbol', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=50)),
                ('atomic_mass', models.CharField(max_length=20)),
                ('electronic_configuration', models.CharField(max_length=50)),
                ('electronegativity', models.FloatField(blank=True, null=True)),
                ('atomic_radius', models.PositiveIntegerField(blank=True, null=True)),
                ('ion_radius', models.CharField(blank=True, max_length=20, null=True)),
                ('van_der_waals_radius', models.PositiveIntegerField(blank=True, null=True)),
                ('ionization_energy', models.FloatField(blank=True, null=True)),
                ('electron_affinity', models.FloatField(blank=True, null=True)),
                ('oxidation_states', models.CharField(blank=True, max_length=20, null=True)),
                ('standard_state', models.CharField(blank=True, max_length=20, null=True)),
                ('bonding_type', models.CharField(blank=True, max_length=20, null=True)),
                ('melting_point', models.PositiveIntegerField(blank=True, null=True)),
                ('boiling_point', models.PositiveIntegerField(blank=True, null=True)),
                ('density', models.FloatField(blank=True, null=True)),
                ('group_block', models.CharField(blank=True, max_length=20, null=True)),
                ('year_discovered', models.PositiveIntegerField(blank=True, null=True)),
                ('block', models.CharField(blank=True, max_length=1, null=True)),
                ('cpk_hex_color', models.CharField(blank=True, max_length=6, null=True)),
                ('period', models.PositiveIntegerField(blank=True, null=True)),
                ('group', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
