# Generated by Django 5.1.1 on 2024-09-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalelement',
            name='density',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalelement',
            name='electron_affinity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalelement',
            name='electronegativity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalelement',
            name='ionization_energy',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
