# Generated by Django 5.1.1 on 2024-09-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_chemicalelement_density_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalelement',
            name='atomic_mass',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='chemicalelement',
            name='atomic_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='chemicalelement',
            name='atomic_radius',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalelement',
            name='block',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalelement',
            name='boiling_point',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalelement',
            name='bonding_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalelement',
            name='cpk_hex_color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalelement',
            name='density',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalelement',
            name='electron_affinity',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalelement',
            name='electronegativity',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalelement',
            name='electronic_configuration',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='chemicalelement',
            name='group',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalelement',
            name='group_block',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalelement',
            name='ion_radius',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalelement',
            name='ionization_energy',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalelement',
            name='melting_point',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalelement',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='chemicalelement',
            name='oxidation_states',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalelement',
            name='period',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalelement',
            name='standard_state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalelement',
            name='symbol',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='chemicalelement',
            name='van_der_waals_radius',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalelement',
            name='year_discovered',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
